[BUGFIX] set header via response api
einpraegsam/powermail pull request #850
Opened 2023-01-10 12:36 UTC by lukasniestroj

$this->htmlResponse() will overwrite the "Content-Type" header in its function call, so it is always "text/html" which will not trigger a download if you export via the backend module

2023-01-11 08:42 UTC, einpraegsam requested changes
Thx for your change. I tend to merge it, but changing content-disposition from "attachment" to "inline" is a small breaking change that I would prevent here.

2023-01-11 09:35 UTC, lukasniestroj commented
Sorry, copy paste 🤣. Will fix that asap.

Alexander Kellner ***@***.***> schrieb am Mi., 11. Jan. 2023,
09:42:

> ***@***.**** requested changes on this pull request.
>
> Thx for your change. I tend to merge it, but changing content-disposition
> from "attachment" to "inline" is a small breaking change that I would
> prevent here.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/einpraegsam/powermail/pull/850#pullrequestreview-1243488983>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AF7RD33KNRQONWDVMCCWR33WRZXAJANCNFSM6AAAAAATWXAW3U>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-01-26 12:44 UTC, lukasniestroj reviewed
@einpraegsam can you review again?

2023-01-26 13:31 UTC, merged

2023-01-26 13:31 UTC, einpraegsam commented
Thx for your work. Just merged into develop.